SELECT
School19 = (CASE STU.SC
WHEN 2 THEN 'El Toro'
WHEN 6 THEN 'Los Paseos'
WHEN 8 THEN 'Nordstrom'
WHEN 9 THEN 'Paradise'
WHEN 10 THEN 'SMG'
WHEN 11 THEN 'Walsh'
WHEN 12 THEN 'Barrett'
WHEN 15 THEN 'JAMM'
WHEN 20 THEN 'Britton'
WHEN 21 THEN 'Murphy'
WHEN 30 THEN 'Central'
WHEN 31 THEN 'Live Oak'
WHEN 32 THEN 'Sobrato'
END),
STU.GR,
COUNT(STU.ID) AS 'Total Students'
FROM STU
WHERE STU.TG = ''
AND STU.DEL = 0
AND STU.SC IN (2,6,8,9,10,11,12,15)
AND STU.GR < 6
AND STU.GR > -3
GROUP BY SC,GR
ORDER BY SC, GR
