SELECT
[ID] = STU.ID,
[Name] = STU.LN + ', ' + STU.FN,
[Grade] = STU.GR,
[SPED] = STU.U2,
[LangFluency] = CASE STU.LF
  WHEN 'E' THEN 'English Only'
  WHEN 'L' THEN 'English Learner'
  WHEN 'R' THEN 'Redesignated'
  WHEN 'C' THEN 'Cum'
  WHEN 'I' THEN 'Initially Fluent'
  WHEN 'T' THEN 'TBD'
  WHEN 'N' THEN 'Needs Testing'
END,
-- ISNULL ((SELECT TOP (1) CAST(PL AS FLOAT) AS score FROM dbo.TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'F&P') AND (TA = 'BL1920') AND (PT = 0) ORDER BY TD DESC ),'') AS [F&P Fall 2019],
ISNULL ((SELECT TOP (1) ROUND(SCR, 1) AS score FROM dbo.GBS WHERE (GBS.DEL = 0) AND (GBS.SN = stu.SN) AND (GBS.SC = STU.SC) AND (GBS.AN = 900) AND (GBS.DC IS NOT NULL) ORDER BY DC DESC ),'') as [F&P Fall 2019],
CASE ISNULL ((SELECT TOP (1) ROUND(SCR, 1) AS score FROM dbo.GBS WHERE (STU.DEL = 0) AND (GBS.SN = stu.SN) AND (GBS.SC = STU.SC) AND (GBS.AN = 900) AND (GBS.DC IS NOT NULL) ORDER BY DC DESC ),'')
  WHEN 0.3 THEN 'A'
  WHEN 0.6 THEN 'B'
  WHEN 0.9 THEN 'C'
  WHEN 1.2 THEN 'D'
  WHEN 1.4 THEN 'E'
  WHEN 1.5 THEN 'F'
  WHEN 1.6 THEN 'G'
  WHEN 1.8 THEN 'H'
  WHEN 1.9 THEN 'I'
  WHEN 2.3 THEN 'J'
  WHEN 2.6 THEN 'K'
  WHEN 2.9 THEN 'L'
  WHEN 3.3 THEN 'M'
  WHEN 3.6 THEN 'N'
  WHEN 3.9 THEN 'O'
  WHEN 4.3 THEN 'P'
  WHEN 4.6 THEN 'Q'
  WHEN 4.9 THEN 'R'
  WHEN 5.3 THEN 'S'
  WHEN 5.6 THEN 'T'
  WHEN 5.9 THEN 'U'
  WHEN 6.3 THEN 'V'
  WHEN 6.6 THEN 'W'
  WHEN 6.9 THEN 'X'
  WHEN 7.3 THEN 'Y'
  WHEN 7.6 THEN 'Z'
  ELSE 'No Score'
END AS [F&P],
MAP_ELAScore_Fall19 = ISNULL ((SELECT TOP (1) SS AS score FROM TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'MAP') AND (PT = 1) AND (TA IN ('1909','1910','1908')) ORDER BY TD DESC ),''),
MAP_ELAPercentile_Fall19 = ISNULL ((SELECT TOP (1) PC AS score FROM TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'MAP') AND (PT = 1) AND (TA IN ('1909','1910','1908')) ORDER BY TD DESC ),''),
MAP_MathScore_Fall19 = ISNULL ((SELECT TOP (1) SS AS score FROM TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'MAP') AND (PT = 20) AND (TA IN ('1909','1910','1908')) ORDER BY TD DESC ),''),
MAP_MathPercentile_Fall19 = ISNULL ((SELECT TOP (1) PC AS score FROM TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'MAP') AND (PT = 20) AND (TA IN ('1909','1910','1908')) ORDER BY TD DESC ),''),
ELPAC_Overall_Perf =  NULLIF(ISNULL ((SELECT TOP (1) cast( PL AS INT) AS score FROM TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'ELPAC') AND (PT = 0) ORDER BY TD DESC ),''), 0),
ELPAC_Overall_Score =  NULLIF(ISNULL ((SELECT TOP (1) cast( SS AS INT) AS score FROM TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'ELPAC') AND (PT = 0) ORDER BY TD DESC ),''), 0),
CAST((CAST(SUM(AHS.PR) AS FLOAT)/(CAST(SUM(AHS.EN) AS FLOAT))) AS DECIMAL (10,2)) AS 'Percentage'
FROM STU
JOIN AHS
	ON(AHS.ID = STU.ID)
WHERE STU.DEL = 0
AND STU.TG = ''
AND AHS.EN > 0
AND AHS.YR = '2019-2020'
AND STU.SC = 9
GROUP BY STU.ID, STU.LN, STU.FN, STU.GR, STU.SC, STU.SN, STU.U2, STU.LF, STU.DEL
