SELECT
[ID] = STU.ID,
[Name] = STU.LN + ', ' + STU.FN,
School = CASE STU.SC
WHEN 2 THEN 'El Toro'
WHEN 6 THEN 'Los Paseos'
WHEN 8 THEN 'Nordstrom'
WHEN 9 THEN 'Paradise'
WHEN 10 THEN 'SMG'
WHEN 11 THEN 'Walsh'
WHEN 12 THEN 'Barrett'
WHEN 15 THEN 'JAMM'
WHEN 20 THEN 'Britton'
WHEN 21 THEN 'Murphy'
WHEN 30 THEN 'Central'
WHEN 31 THEN 'Live Oak'
WHEN 32 THEN 'Sobrato'
END,
[Grade] = STU.GR,
ISNULL ((SELECT TOP (1) ROUND(SCR, 1) AS score FROM dbo.GBS WHERE (GBS.DEL = 0) AND (GBS.SN = stu.SN) AND (GBS.SC = STU.SC) AND (GBS.AN = 900) AND (GBS.DC IS NOT NULL) ORDER BY DC DESC ),'') as [F&P Fall 2019 Real],
CASE ISNULL ((SELECT TOP (1) ROUND(SCR, 1) AS score FROM dbo.GBS WHERE (STU.DEL = 0) AND (GBS.SN = stu.SN) AND (GBS.SC = STU.SC) AND (GBS.AN = 900) AND (GBS.DC IS NOT NULL) ORDER BY DC DESC ),'')
  WHEN 0.3 THEN 'A'
  WHEN 0.6 THEN 'B'
  WHEN 0.9 THEN 'C'
  WHEN 1.2 THEN 'D'
  WHEN 1.4 THEN 'E'
  WHEN 1.5 THEN 'F'
  WHEN 1.6 THEN 'G'
  WHEN 1.8 THEN 'H'
  WHEN 1.9 THEN 'I'
  WHEN 2.3 THEN 'J'
  WHEN 2.6 THEN 'K'
  WHEN 2.9 THEN 'L'
  WHEN 3.3 THEN 'M'
  WHEN 3.6 THEN 'N'
  WHEN 3.9 THEN 'O'
  WHEN 4.3 THEN 'P'
  WHEN 4.6 THEN 'Q'
  WHEN 4.9 THEN 'R'
  WHEN 5.3 THEN 'S'
  WHEN 5.6 THEN 'T'
  WHEN 5.9 THEN 'U'
  WHEN 6.3 THEN 'V'
  WHEN 6.6 THEN 'W'
  WHEN 6.9 THEN 'X'
  WHEN 7.3 THEN 'Y'
  WHEN 7.6 THEN 'Z'
  ELSE 'No Score'
END AS [F&P GB],
ReadingScore_Fall19_MAP = ISNULL ((SELECT TOP (1) SS AS score FROM TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'MAP') AND (PT = 1) AND (TA IN ('1908','1909','1910','1911')) ORDER BY TD DESC ),'')
FROM STU
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.GR > -1
AND STU.GR < 4
AND STU.SC IN (2,6,8,9,10,11,12,15)
ORDER BY STU.SC, STU.GR, STU.LN, STU.FN

SELECT
[ID] = STU.ID,
[Name] = STU.LN + ', ' + STU.FN,
School = CASE STU.SC
WHEN 2 THEN 'El Toro'
WHEN 6 THEN 'Los Paseos'
WHEN 8 THEN 'Nordstrom'
WHEN 9 THEN 'Paradise'
WHEN 10 THEN 'SMG'
WHEN 11 THEN 'Walsh'
WHEN 12 THEN 'Barrett'
WHEN 15 THEN 'JAMM'
WHEN 20 THEN 'Britton'
WHEN 21 THEN 'Murphy'
WHEN 30 THEN 'Central'
WHEN 31 THEN 'Live Oak'
WHEN 32 THEN 'Sobrato'
END,
[Grade] = STU.GR,
ELAScore_Fall19_MAP = ISNULL ((SELECT TOP (1) SS AS score FROM TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'MAP') AND (PT = 1) AND (TA IN ('1908','1909','1910','1911')) ORDER BY TD DESC ),''),
MathScore_Fall19_MAP = ISNULL ((SELECT TOP (1) SS AS score FROM TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'MAP') AND (PT = 20) AND (TA IN ('1908','1909','1910','1911')) ORDER BY TD DESC ),''),
SciScore_Fall19_MAP = ISNULL ((SELECT TOP (1) SS AS score FROM TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'MAP') AND (PT = 40) AND (TA IN ('1908','1909','1910','1911')) ORDER BY TD DESC ),'')
FROM STU
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.GR = 8
AND STU.SC IN (10,15,21,20)
ORDER BY STU.SC, STU.GR, STU.LN, STU.FN