SELECT
STU.ID,
STU.LN + ', ' + STU.FN AS 'Name',
STU.SC,
STU.GR,
STU.TL,
CASE WHEN STU.PEM = ''
THEN (SELECT TOP(1) EM FROM CON WHERE CON.PID = STU.ID AND CON.LW = 'Y' AND CON.EM !=' ' ORDER BY [OR] DESC)
ELSE STU.PEM END
FROM STU
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.SC IN (2,6,8,9,10,11,12,15,20,21,30,31,32)
