USE Aeries

SELECT
STU.ID,
STU.FN,
STU.LN,
STU.GR,
STU.ETH,
[Race] = (CASE
	WHEN STU.ETH = 'Y' AND STU.RC1 > 100 THEN 'Hispanic'
	WHEN STU.RC1 = 100 THEN 'American Indian or Alaskan Native'
	WHEN STU.RC1 > 200 AND STU.RC1 < 300 THEN 'Asian'
	WHEN STU.RC1 > 300 AND STU.RC1 < 401 THEN 'Pacific Islander'
	WHEN STU.RC1 = 600 THEN 'Black or African American'
	WHEN STU.RC1 = 700 THEN 'White'
	ELSE 'Unknown'
END),
STU.U4 AS 'Migrant',
STU.U2 AS 'SPED',
STU.LF AS 'LangFluency',
(SELECT TE FROM TCH WHERE STU.CU = TCH.TN AND STU.SC = TCH.SC and TCH.DEL = 0 ) AS Teacher,
School = ( SELECT LOC.NM FROM LOC WHERE STU.SC = LOC.CD),
SUM(AHS.PR) AS 'Days Present',
SUM(AHS.EN) AS 'Days Enrolled',
SUM(AHS.AB) AS 'Days Absent',
SUM(AHS.SU) AS 'Days Suspended',
CAST((CAST(SUM(AHS.PR) AS FLOAT)/(CAST(SUM(AHS.EN) AS FLOAT))) AS DECIMAL (10,2)) AS 'Percentage',
[Chronic] = (CASE WHEN
	(CAST((CAST(SUM(AHS.PR) AS FLOAT)/(CAST(SUM(AHS.EN) AS FLOAT))) AS DECIMAL (10,2))) < .8 THEN 'Y'
	ELSE 'N'
END)
FROM STU
JOIN AHS
	ON(AHS.ID = STU.ID)
WHERE AHS.EN != 0
AND AHS.YR ='2018-2019'
AND STU.DEL = 0
AND STU.TG = ''
AND STU.SC IN (2,6,8,9,10,11,12,15,20,21,30,31,32)
GROUP BY STU.ID, STU.FN, STU.LN, STU.GR, STU.CU, STU.SC, STU.ETH, STU.U4, STU.U2, STU.LF, STU.RC1, STU.ETH
