USE Aeries

SELECT 
STU.SC,
STU.GR,
COUNT(STU.ID) AS 'Total Students'
FROM STU
WHERE STU.TG = ''
AND STU.DEL = 0
AND STU.SC IN (2,6,8,9,10,11,12,15)
AND STU.GR < 6
AND STU.GR > -1
GROUP BY SC,GR
ORDER BY SC, GR