USE Aeries

SELECT
StudentID = (SELECT STU.ID FROM STU WHERE STU.SC = GRH.SC AND STU.SN = GRH.SN),
StudentLastName = (SELECT STU.LN FROM STU WHERE STU.SC = GRH.SC AND STU.SN = GRH.SN),
StudentFirstName = (SELECT STU.FN FROM STU WHERE STU.SC = GRH.SC AND STU.SN = GRH.SN),
(SELECT STU.GR FROM STU WHERE STU.SC = GRH.SC AND STU.SN = GRH.SN) AS 'Grade',
GRH.WM AS 'Marking Period',
CRS.CO AS 'Course Title',
CRS.NA AS 'Honors/N',
[Department] = (CASE CRS.DC
WHEN 'E' THEN 'English'
WHEN 'I' THEN 'Science'
WHEN 'K' THEN 'Social Studies'
WHEN 'M' THEN 'Math'
END),
CRS.DC AS 'Department Code',
GRH.MK AS 'Semester Grade',
[Weight] = (CASE
WHEN GRH.MK = 'A+' AND CRS.NA = 'H' THEN 5
WHEN GRH.MK = 'A' AND CRS.NA = 'H' THEN 5
WHEN GRH.MK = 'A-' AND CRS.NA = 'H' THEN 5
WHEN GRH.MK = 'B+' AND CRS.NA = 'H' THEN 4
WHEN GRH.MK = 'B' AND CRS.NA = 'H' THEN 4
WHEN GRH.MK = 'B-' AND CRS.NA = 'H' THEN 4
WHEN GRH.MK = 'C+' AND CRS.NA = 'H' THEN 3
WHEN GRH.MK = 'C' AND CRS.NA = 'H' THEN 3
WHEN GRH.MK = 'C-' AND CRS.NA = 'H' THEN 3
WHEN GRH.MK = 'D+' AND CRS.NA = 'H' THEN 1
WHEN GRH.MK = 'D' AND CRS.NA = 'H' THEN 1
WHEN GRH.MK = 'D-' AND CRS.NA = 'H' THEN 1
WHEN GRH.MK = 'F' AND CRS.NA = 'H' THEN 0
WHEN GRH.MK = 'A+' AND CRS.NA = '' THEN 4
WHEN GRH.MK = 'A' AND CRS.NA = '' THEN 4
WHEN GRH.MK = 'A-' AND CRS.NA = '' THEN 4
WHEN GRH.MK = 'B+' AND CRS.NA = '' THEN 3
WHEN GRH.MK = 'B' AND CRS.NA = '' THEN 3
WHEN GRH.MK = 'B-' AND CRS.NA = '' THEN 3
WHEN GRH.MK = 'C+' AND CRS.NA = '' THEN 2
WHEN GRH.MK = 'C' AND CRS.NA = '' THEN 2
WHEN GRH.MK = 'C-' AND CRS.NA = '' THEN 2
WHEN GRH.MK = 'D+' AND CRS.NA = '' THEN 1
WHEN GRH.MK = 'D' AND CRS.NA = '' THEN 1
WHEN GRH.MK = 'D-' AND CRS.NA = '' THEN 1
ELSE 0
END),
GRH.CR AS 'Credit',
SPED = (SELECT STU.U2 FROM STU WHERE STU.SC = GRH.SC AND STU.SN = GRH.SN)
FROM GRH
JOIN CRS ON
  (GRH.CN = CRS.CN)
WHERE GRH.DEL = 0
AND GRH.SC = 30
AND CRS.DC IN ('K', 'I', 'E', 'M')
AND GRH.WM IN (2,4,6,8,10,12)
AND GRH.MK != ' '
ORDER BY 'Marking Period', Department, Grade, 'Course Title'
