USE Aeries

SELECT
LEFT(STU.FN, 1) AS 'FIRST',
LEFT(STU.MN, 1) AS 'MIDDLE',
LEFT(STU.LN, 1) AS 'LAST',
STU.ID AS 'STUDENT_ID',
SCHOOL = (SELECT LOC.NM FROM LOC WHERE STU.SC = LOC.CD),
STU.GR AS 'GRADE',
STU.SX AS 'GENDER',
[RACE_ETH] = (CASE
	WHEN STU.ETH = 'Y' AND STU.RC1 > 100 THEN 'HISPANIC/LATINO'
	WHEN STU.RC1 = 100 THEN 'AMER IND/ALASK'
	WHEN STU.RC1 > 200 AND STU.RC1 < 300 THEN 'ASIAN'
	WHEN STU.RC1 > 300 AND STU.RC1 < 401 THEN 'PAC ISL'
	WHEN STU.RC1 = 600 THEN 'AFRICAN AMER'
	WHEN STU.RC1 = 700 THEN 'WHITE'
	ELSE 'UNKNOWN'
END),
STU.ZC AS 'ZIP',
'IEP' = (CASE STU.U2 WHEN 'Y' THEN 'YES' ELSE 'NO' END),
[EL] = CASE STU.LF WHEN 'L' THEN 'YES' ELSE 'NO' END,
'FRL' = (case when stu.id in (select fre.id from fre where fre.id = stu.id and fre.cd in ( 'f', 'r' ) and  (fre.esd > '7/1/2019' and fre.eed = '6/30/2020' ) and fre.del = 0 and ( stu.ped = 14 or fre.cd is not null )) then 'YES' else 'NO' end),
Present = (SELECT TOP(1) AHS.PR FROM AHS WHERE AHS.ID = STU.ID AND AHS.YR = '2019-2020'),
Excused = (SELECT TOP(1) AHS.AE FROM AHS WHERE AHS.ID = STU.ID AND AHS.YR = '2019-2020'),
Unexcused = (SELECT TOP(1) AHS.AU FROM AHS WHERE AHS.ID = STU.ID AND AHS.YR = '2019-2020'),
'Days_Susp' = (SELECT SUM(AHS.SU) FROM AHS WHERE AHS.ID = STU.ID AND AHS.YR = '2019-2020'),
'Suspensions' = (SELECT COUNT(DSP.DS) FROM DSP WHERE DSP.PID = STU.ID AND DSP.DS = 'SUS' AND DSP.DD > '5/30/2019'),
'Not' = RIGHT((SELECT TOP(1) LTL.ID FROM LTL WHERE LTL.PID = STU.ID AND LTL.DT > '08/15/2019' AND LEFT(LTL.ID, 1)= 'A' ORDER BY DT DESC), 1),
'NO' AS 'Abs_Letter'
FROM STU
WHERE STU.TG = ''
AND STU.DEL = 0
AND STU.GR < 6
AND STU.SC IN (2,6,8,9,10,11,12,15)
