SELECT 
ATT.DT,
STU.FN, 
STU.LN, 
STU.GR, 
STU.ID, 
ATT.AL,
ISNULL((SELECT TOP(1) CO FROM ATN WHERE ATN.SC = ATT.SC AND ATT.SN = ATN.SN AND ATN.DT = ATT.DT),'')
FROM ATT
JOIN STU ON ATT.SC = STU.SC AND ATT.SN = STU.SN 
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.SC = 10
ORDER BY STU.LN, STU.FN