SELECT
ID = STU.ID,
Name = STU.LN + ', ' + STU.FN,
Grade = STU.GR,
SPED = STU.U2,
-- Attendance_Perc = CAST(
-- 	((SELECT CAST(SUM(AHS.PR) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'))/((SELECT CAST(SUM(AHS.EN) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'))
-- AS DECIMAL(10,2)),
-- Days_Present = (SELECT CAST(SUM(AHS.PR) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'),
-- Days_Enrolled = (SELECT CAST(SUM(AHS.EN) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'),
-- Tardies = ISNULL((SELECT SUM(TD) FROM AHS WHERE (YR = '2019-2020') AND (AHS.ID = STU.ID)),''),
Date_dis = ADS.DT,
Referrer = ADS.RF,
Comments = ADS.CO,
ViolationCD = ADS.CD,
ViolationCD2 = ADS.CD2
FROM STU
JOIN ADS ON STU.ID = ADS.PID
WHERE STU.DEL = 0
AND STU.SC = 9
AND ADS.DT > '2019-08-15'
ORDER BY ADS.DT



-- Regular dis
SELECT
ID = STU.ID,
Name = STU.LN + ', ' + STU.FN,
Grade = STU.GR,
SPED = STU.U2,
--Attendance_Perc = CAST(
--	((SELECT CAST(SUM(AHS.PR) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'))/((SELECT CAST(SUM(AHS.EN) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'))
--AS DECIMAL(10,2)),
--Days_Present = (SELECT CAST(SUM(AHS.PR) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'),
--Days_Enrolled = (SELECT CAST(SUM(AHS.EN) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'),
--Tardies = ISNULL((SELECT SUM(TD) FROM AHS WHERE (YR = '2019-2020') AND (AHS.ID = STU.ID)),''),
Discipline_Date = DIS.DT,
Discipline_Comment = DIS.CO
FROM STU
JOIN DIS ON STU.ID = DIS.PID
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.SC = 9
AND DIS.DT > '2019-08-15'
ORDER BY Grade, Name

-- Total
SELECT
ID = STU.ID,
Name = STU.LN + ', ' + STU.FN,
Grade = STU.GR,
SPED = STU.U2,
Attendance_Perc = CAST(
	((SELECT CAST(SUM(AHS.PR) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'))/((SELECT CAST(SUM(AHS.EN) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'))
AS DECIMAL(10,2)),
Days_Present = (SELECT CAST(SUM(AHS.PR) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'),
Days_Enrolled = (SELECT CAST(SUM(AHS.EN) AS FLOAT) FROM AHS WHERE (AHS.ID = STU.ID) AND AHS.YR = '2019-2020'),
Tardies = ISNULL((SELECT SUM(TD) FROM AHS WHERE (YR = '2019-2020') AND (AHS.ID = STU.ID)),'')
FROM STU
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.SC = 10
ORDER BY Grade, Name
