SELECT
STU.ID AS "ID",
STU.SC AS "School Code",
School = ( select LOC.NM from LOC where stu.SC = LOC.CD),
STU.GR AS "Grade",
School15_16 = (CASE (SELECT TOP (1) ENR.SC FROM ENR WHERE STU.ID = ENR.ID AND ENR.YR = 2015)
WHEN 2 THEN 'El Toro'
WHEN 6 THEN 'Los Paseos'
WHEN 8 THEN 'Nordstrom'
WHEN 9 THEN 'Paradise'
WHEN 10 THEN 'SMG'
WHEN 11 THEN 'Walsh'
WHEN 12 THEN 'Barrett'
WHEN 15 THEN 'JAMM'
WHEN 20 THEN 'Britton'
WHEN 21 THEN 'Murphy'
WHEN 30 THEN 'Central'
WHEN 31 THEN 'Live Oak'
WHEN 32 THEN 'Sobrato'
END),
School14_15 = (CASE (SELECT TOP (1) ENR.SC FROM ENR WHERE STU.ID = ENR.ID AND ENR.YR = 2014)
WHEN 2 THEN 'El Toro'
WHEN 6 THEN 'Los Paseos'
WHEN 8 THEN 'Nordstrom'
WHEN 9 THEN 'Paradise'
WHEN 10 THEN 'SMG'
WHEN 11 THEN 'Walsh'
WHEN 12 THEN 'Barrett'
WHEN 15 THEN 'JAMM'
WHEN 20 THEN 'Britton'
WHEN 21 THEN 'Murphy'
WHEN 30 THEN 'Central'
WHEN 31 THEN 'Live Oak'
WHEN 32 THEN 'Sobrato'
END),
School13_14 = (CASE (SELECT TOP (1) ENR.SC FROM ENR WHERE STU.ID = ENR.ID AND ENR.YR = 2013)
WHEN 2 THEN 'El Toro'
WHEN 6 THEN 'Los Paseos'
WHEN 8 THEN 'Nordstrom'
WHEN 9 THEN 'Paradise'
WHEN 10 THEN 'SMG'
WHEN 11 THEN 'Walsh'
WHEN 12 THEN 'Barrett'
WHEN 15 THEN 'JAMM'
WHEN 20 THEN 'Britton'
WHEN 21 THEN 'Murphy'
WHEN 30 THEN 'Central'
WHEN 31 THEN 'Live Oak'
WHEN 32 THEN 'Sobrato'
END),
ELAScore2019_CAASPP =  ISNULL ((SELECT TOP (1) SS AS score FROM dbo.TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'SBAC') AND (TA = 'SPRG19') AND (PT = 1) ORDER BY TD DESC ),''),
ELAPCL2019_CAASPP =  ISNULL ((SELECT TOP (1) cast( PL as int) AS score FROM dbo.TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'SBAC') AND (TA = 'SPRG19') AND (PT = 1) ORDER BY TD DESC ),''),
MathScore2019_CAASPP =  ISNULL ((SELECT TOP (1) SS AS score FROM dbo.TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'SBAC') AND (TA = 'SPRG19') AND (PT = 2) ORDER BY TD DESC ),''),
MathPCL2019_CAASPP =  ISNULL ((SELECT TOP (1) cast( PL as int) AS score FROM dbo.TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'SBAC') AND (TA = 'SPRG19') AND (PT = 2) ORDER BY TD DESC ),'')
FROM STU
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.SC in (2,6,8,9,10,11,12,15,20,21,30,31,32,40,60,70)
AND STU.GR > 3
ORDER BY School
