SELECT
TCH.TE AS Teacher,
School = ( select LOC.NM from LOC where GBK.SC = LOC.CD),
GBA.AD,
Complete = (CASE GBA.GC WHEN 0 THEN 'False' ELSE 'True' END),
GBA.GC,
GBK.HI,
GBK.LO
FROM GBK
JOIN GBA ON (GBK.GN = GBA.GN)
JOIN TCH ON (GBK.TN = TCH.TN) AND (GBK.SC = TCH.SC)
WHERE GBA.AN = 902

AND GBK.HI > -1
AND GBK.LO < 6
AND TCH.DEL = 0
AND TCH.TG = ''
--AND GBK.SC = 10
ORDER BY School, Complete desc
