SELECT
[ID] = STU.ID,
[Name] = STU.LN + ', ' + STU.FN,
Teacher = (select TE from TCH where stu.CU = TCH.TN and stu.sc = tch.sc and tch.del = 0 ),
[Grade] = STU.GR,
ISNULL ((SELECT TOP (1) ROUND(SCR, 1) AS score FROM dbo.GBS WHERE (GBS.DEL = 0) AND (GBS.SN = stu.SN) AND (GBS.SC = STU.SC) AND (GBS.AN = 900) AND (GBS.DC IS NOT NULL) ORDER BY DC DESC ),'') as [F&P Fall 2020],
CASE ISNULL ((SELECT TOP (1) ROUND(SCR, 1) AS score FROM dbo.GBS WHERE (STU.DEL = 0) AND (GBS.SN = stu.SN) AND (GBS.SC = STU.SC) AND (GBS.AN = 900) AND (GBS.DC IS NOT NULL) ORDER BY DC DESC ),'')
  WHEN 0.3 THEN 'A'
  WHEN 0.6 THEN 'B'
  WHEN 0.9 THEN 'C'
  WHEN 1.2 THEN 'D'
  WHEN 1.4 THEN 'E'
  WHEN 1.5 THEN 'F'
  WHEN 1.6 THEN 'G'
  WHEN 1.8 THEN 'H'
  WHEN 1.9 THEN 'I'
  WHEN 2.3 THEN 'J'
  WHEN 2.6 THEN 'K'
  WHEN 2.9 THEN 'L'
  WHEN 3.3 THEN 'M'
  WHEN 3.6 THEN 'N'
  WHEN 3.9 THEN 'O'
  WHEN 4.3 THEN 'P'
  WHEN 4.6 THEN 'Q'
  WHEN 4.9 THEN 'R'
  WHEN 5.3 THEN 'S'
  WHEN 5.6 THEN 'T'
  WHEN 5.9 THEN 'U'
  WHEN 6.3 THEN 'V'
  WHEN 6.6 THEN 'W'
  WHEN 6.9 THEN 'X'
  WHEN 7.3 THEN 'Y'
  WHEN 7.6 THEN 'Z'
  ELSE 'No Score'
END AS [F&P Fall],
ISNULL ((SELECT TOP (1) ROUND(SCR, 1) AS score FROM dbo.GBS WHERE (GBS.DEL = 0) AND (GBS.SN = stu.SN) AND (GBS.SC = STU.SC) AND (GBS.AN = 902) AND (GBS.DC IS NOT NULL) ORDER BY DC DESC ),'') as [F&P Spring 2021],
CASE ISNULL ((SELECT TOP (1) ROUND(SCR, 1) AS score FROM dbo.GBS WHERE (STU.DEL = 0) AND (GBS.SN = stu.SN) AND (GBS.SC = STU.SC) AND (GBS.AN = 902) AND (GBS.DC IS NOT NULL) ORDER BY DC DESC ),'')
  WHEN 0.3 THEN 'A'
  WHEN 0.6 THEN 'B'
  WHEN 0.9 THEN 'C'
  WHEN 1.2 THEN 'D'
  WHEN 1.4 THEN 'E'
  WHEN 1.5 THEN 'F'
  WHEN 1.6 THEN 'G'
  WHEN 1.8 THEN 'H'
  WHEN 1.9 THEN 'I'
  WHEN 2.3 THEN 'J'
  WHEN 2.6 THEN 'K'
  WHEN 2.9 THEN 'L'
  WHEN 3.3 THEN 'M'
  WHEN 3.6 THEN 'N'
  WHEN 3.9 THEN 'O'
  WHEN 4.3 THEN 'P'
  WHEN 4.6 THEN 'Q'
  WHEN 4.9 THEN 'R'
  WHEN 5.3 THEN 'S'
  WHEN 5.6 THEN 'T'
  WHEN 5.9 THEN 'U'
  WHEN 6.3 THEN 'V'
  WHEN 6.6 THEN 'W'
  WHEN 6.9 THEN 'X'
  WHEN 7.3 THEN 'Y'
  WHEN 7.6 THEN 'Z'
  ELSE 'No Score'
END AS [F&P Spring]
FROM STU
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.SC = 15
AND STU.GR < 6
ORDER BY STU.GR, Teacher, STU.LN, STU.FN
