

SELECT
STU.LN AS "Last_Name",
STU.FN AS "First_Name",
STU.ID AS "SIS_ID",
STU.GR AS "Grade",
STU.ID AS "User_Name",
'School_Name' = (CASE STU.SC
WHEN 2 THEN 'EL_TORO_ELEMENTARY_SCHOOL'
WHEN 6 THEN 'LOS_PASEOS'
WHEN 8 THEN 'NORDSTROM_ELEMENTARY_SCHOOL'
WHEN 9 THEN 'PARADISE_ELEMENTARY_SCHOOL'
WHEN 10 THEN 'SAN_MARTIN_ELEMENTARY_SCHOOL'
WHEN 11 THEN 'WALSH_ELEMENTARY_SCHOOL'
WHEN 12 THEN 'BARRETT_MIDDLE_SCHOOL'
WHEN 15 THEN 'JACKSON_ACADEMY'
WHEN 20 THEN 'BRITTON_MIDDLE_SCHOOL'
WHEN 21 THEN 'MURPHY_MIDDLE_SCHOOL'
WHEN 30 THEN 'CENTRAL_HIGH_SCHOOL'
WHEN 31 THEN 'LIVE_OAK_HIGH_SCHOOL'
WHEN 32 THEN 'ANN_SOBRATO_HIGH_SCHOOL'
END),
[Class_Name] = CAST(STU.GR AS VARCHAR) + 'th Grade'
FROM STU
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.SC IN (2,6,8,9,10,11,12,15,20,21,30,31,32)
