SELECT
STU.ID,
STU.FN,
STU.LN,
STU.GR,
School = ( select LOC.NM from LOC where stu.SC = LOC.CD),
ISNULL((SELECT max(PWA.CDT) AS logi WHERE (PWA.TY = 'P')),NULL) AS "Last Accessed"
FROM STU
JOIN PWS
	ON PWS.ID = STU.ID
JOIN PWA
	ON PWA.AID = PWS.AID
WHERE stu.sc in (2,6,8,9,10,11,12,15,20,21,30,31,32)
AND STU.DEL = 0
AND STU.TG = ''
AND PWA.TY = 'P'
GROUP BY STU.ID, STU.FN, STU.LN, STU.GR, STU.SC, PWA.TY
ORDER BY STU.SC, STU.GR, STU.LN, STU.FN
