SELECT
STU.ID AS [ID],
Name = STU.LN + ', ' + STU.FN,
GRH.WM AS 'MK#',
GRH.PD AS 'Period',
GRH.CN AS 'Crs-ID',
CRS.CO AS 'Course Title',
GRH.MK AS 'Mark'
FROM GRH
JOIN STU ON STU.SC = GRH.SC AND STU.SN = GRH.SN
JOIN CRS ON CRS.CN = GRH.CN
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.ID = 101870
