USE Aeries2017

SELECT
StudentID = (SELECT STU.ID FROM STU WHERE STU.SC = GRD.SC AND STU.SN = GRD.SN),
StudentLastName = (SELECT STU.LN FROM STU WHERE STU.SC = GRD.SC AND STU.SN = GRD.SN),
StudentFirstName = (SELECT STU.FN FROM STU WHERE STU.SC = GRD.SC AND STU.SN = GRD.SN),
(SELECT STU.GR FROM STU WHERE STU.SC = GRD.SC AND STU.SN = GRD.SN) AS 'Grade',
CRS.CO AS 'Course Title',
CRS.NA AS 'Honors/N',
[Department] = (CASE CRS.DC
WHEN 'E' THEN 'English'
WHEN 'I' THEN 'Science'
WHEN 'K' THEN 'Social Studies'
WHEN 'M' THEN 'Math'
END),
CRS.DC AS 'Department Code',
GRD.M4 AS '1st Semester Grade',
[SEM 1 Weight] = (CASE
WHEN GRD.M4 = 'A+' AND CRS.NA = 'H' THEN 5
WHEN GRD.M4 = 'A' AND CRS.NA = 'H' THEN 5
WHEN GRD.M4 = 'A-' AND CRS.NA = 'H' THEN 5
WHEN GRD.M4 = 'B+' AND CRS.NA = 'H' THEN 4
WHEN GRD.M4 = 'B' AND CRS.NA = 'H' THEN 4
WHEN GRD.M4 = 'B-' AND CRS.NA = 'H' THEN 4
WHEN GRD.M4 = 'C+' AND CRS.NA = 'H' THEN 3
WHEN GRD.M4 = 'C' AND CRS.NA = 'H' THEN 3
WHEN GRD.M4 = 'C-' AND CRS.NA = 'H' THEN 3
WHEN GRD.M4 = 'D+' AND CRS.NA = 'H' THEN 1
WHEN GRD.M4 = 'D' AND CRS.NA = 'H' THEN 1
WHEN GRD.M4 = 'D-' AND CRS.NA = 'H' THEN 1
WHEN GRD.M4 = 'F' AND CRS.NA = 'H' THEN 0
WHEN GRD.M4 = 'A+' AND CRS.NA = '' THEN 4
WHEN GRD.M4 = 'A' AND CRS.NA = '' THEN 4
WHEN GRD.M4 = 'A-' AND CRS.NA = '' THEN 4
WHEN GRD.M4 = 'B+' AND CRS.NA = '' THEN 3
WHEN GRD.M4 = 'B' AND CRS.NA = '' THEN 3
WHEN GRD.M4 = 'B-' AND CRS.NA = '' THEN 3
WHEN GRD.M4 = 'C+' AND CRS.NA = '' THEN 2
WHEN GRD.M4 = 'C' AND CRS.NA = '' THEN 2
WHEN GRD.M4 = 'C-' AND CRS.NA = '' THEN 2
WHEN GRD.M4 = 'D+' AND CRS.NA = '' THEN 1
WHEN GRD.M4 = 'D' AND CRS.NA = '' THEN 1
WHEN GRD.M4 = 'D-' AND CRS.NA = '' THEN 1
WHEN GRD.M4 = 'F' AND CRS.NA = '' THEN 0
END),
-- GRD.M8 AS '2nd Semester Grade',
-- [SEM 2 Weight] = (CASE
-- WHEN GRD.M8 = 'A+' AND CRS.NA = 'H' THEN 5
-- WHEN GRD.M8 = 'A' AND CRS.NA = 'H' THEN 5
-- WHEN GRD.M8 = 'A-' AND CRS.NA = 'H' THEN 5
-- WHEN GRD.M8 = 'B+' AND CRS.NA = 'H' THEN 4
-- WHEN GRD.M8 = 'B' AND CRS.NA = 'H' THEN 4
-- WHEN GRD.M8 = 'B-' AND CRS.NA = 'H' THEN 4
-- WHEN GRD.M8 = 'C+' AND CRS.NA = 'H' THEN 3
-- WHEN GRD.M8 = 'C' AND CRS.NA = 'H' THEN 3
-- WHEN GRD.M8 = 'C-' AND CRS.NA = 'H' THEN 3
-- WHEN GRD.M8 = 'D+' AND CRS.NA = 'H' THEN 1
-- WHEN GRD.M8 = 'D' AND CRS.NA = 'H' THEN 1
-- WHEN GRD.M8 = 'D-' AND CRS.NA = 'H' THEN 1
-- WHEN GRD.M8 = 'F' AND CRS.NA = 'H' THEN 0
-- WHEN GRD.M8 = 'A+' AND CRS.NA = '' THEN 4
-- WHEN GRD.M8 = 'A' AND CRS.NA = '' THEN 4
-- WHEN GRD.M8 = 'A-' AND CRS.NA = '' THEN 4
-- WHEN GRD.M8 = 'B+' AND CRS.NA = '' THEN 3
-- WHEN GRD.M8 = 'B' AND CRS.NA = '' THEN 3
-- WHEN GRD.M8 = 'B-' AND CRS.NA = '' THEN 3
-- WHEN GRD.M8 = 'C+' AND CRS.NA = '' THEN 2
-- WHEN GRD.M8 = 'C' AND CRS.NA = '' THEN 2
-- WHEN GRD.M8 = 'C-' AND CRS.NA = '' THEN 2
-- WHEN GRD.M8 = 'D+' AND CRS.NA = '' THEN 1
-- WHEN GRD.M8 = 'D' AND CRS.NA = '' THEN 1
-- WHEN GRD.M8 = 'D-' AND CRS.NA = '' THEN 1
-- WHEN GRD.M8 = 'F' AND CRS.NA = '' THEN 0
-- END),
SPED = (SELECT STU.U2 FROM STU WHERE STU.SC = GRD.SC AND STU.SN = GRD.SN)
FROM GRD
JOIN CRS ON
  (GRD.CN = CRS.CN)
WHERE GRD.DEL = 0
AND GRD.SC = 21
AND CRS.DC in('K', 'I', 'E', 'M')
AND GRD.M4 != ''

ORDER BY Grade, Department
