USE Aeries

SELECT
STU.ID AS 'Student ID',
STU.LN + ', ' + STU.FN AS 'Student Name',
GBU.GR AS 'Student Grade',
GBU.GN AS 'Gradebook #',
GBU.CSC AS 'Overall Score',
GBU.CMK AS 'Overall Mark',
[Weight] = (CASE GBU.CMK
WHEN 'A+' THEN 4
WHEN 'A' THEN 4
WHEN 'A-' THEN 4
WHEN 'B+' THEN 3
WHEN 'B' THEN 3
WHEN 'B-' THEN 3
WHEN 'C+' THEN 2
WHEN 'C' THEN 2
WHEN 'C-' THEN 2
WHEN 'D+' THEN 1
WHEN 'D' THEN 1
WHEN 'D-' THEN 1
WHEN 'F' THEN 0
END),
[Department] = (CASE
WHEN GBK.NM LIKE '%MATH%' THEN 'M'
WHEN GBK.NM LIKE '%ENGLISH%' THEN 'E'
WHEN GBK.NM LIKE '%ELA%' THEN 'E'
WHEN GBK.NM LIKE '%SOCIAL STUDIES%' THEN 'K'
WHEN GBK.NM LIKE '%HISTORY%' THEN 'K'
ELSE 'Review'
END),
GBK.NM AS 'Class Name',
GBK.TM as 'Term'
FROM GBK
JOIN GBU ON (GBK.GN = GBU.GN)
JOIN STU ON (GBU.SC = STU.SC) AND (GBU.SN = STU.SN)
WHERE GBU.SC = 15
AND STU.ID = 106922
AND GBK.D2 < '11/08/2019'
