SELECT
'XTBL_TEST_ADMIN.PROD_TEST_ID' = CAST(STU.ID AS VARCHAR) + CAST(STU.CID AS VARCHAR) + 'Spring20-21' + 'FountasPinnell_4369583', --A
'XTBL_TEST_ADMIN.DISTRICT_CODE' = '4369583', --B
'XTBL_TEST_ADMIN.DISTRICT_STUDENT_ID' = STU.ID, --C
'XTBL_TEST_ADMIN.STATE_STUDENT_ID' = STU.CID, --D
'XTBL_TEST_ADMIN.DISTRICT_SCHOOL_ID' = STU.SC, --E
'XTBL_TEST_ADMIN.TEST_ADMIN_PERIOD' = 'SPRING', --F
'XTBL_TEST_ADMIN.TEST_ADMIN_DATE_STR' = CAST(GBS.DC AS DATE), --G
'XTBL_TEST_ADMIN.TEST_STUDENT_GRADE' = STU.GR, --H
'XTBL_TEST_ADMIN.STUDENT_FIRST_NAME' = STU.FN, --I
'XTBL_TEST_ADMIN.STUDENT_LAST_NAME' = STU.LN, --J
'XTBL_TEST_SCORES.TEST_NUMBER' = 'FountasPinnell_4369583', --K
'XTBL_TEST_SCORES.TEST_PRIMARY_RESULT' = CASE
  -- FALL
  -- WHEN TST.PL < STU.GR - 0.5 THEN 'Benchmark Not Met'
  -- WHEN TST.PL < STU.GR AND TST.PL > STU.GR - 0.5 THEN 'Benchmark Nearly Met'
  -- WHEN TST.PL > STU.GR THEN 'Benchmark Met'
  -- SPRING
  WHEN ROUND(GBS.SCR,2) < STU.GR THEN 'Benchmark Not Met'
  WHEN STU.GR = 1 AND ROUND(GBS.SCR,2) > 1 AND ROUND(GBS.SCR,2) < 1.5 THEN 'Benchmark Nearly Met'
  WHEN STU.GR = 1 AND ROUND(GBS.SCR,2) > 1.4 THEN 'Benchmark Met'
  WHEN ROUND(GBS.SCR,2) < STU.GR + 0.5 AND ROUND(GBS.SCR,2) > STU.GR THEN 'Benchmark Nearly Met'
  WHEN ROUND(GBS.SCR,2) >= STU.GR + 0.5 THEN 'Benchmark Met'
END, --L
'XTBL_TEST_SCORES.TEST_Primary_Result_Code' = CASE
  -- FALL
  -- WHEN TST.PL < STU.GR - 0.5 THEN 1
  -- WHEN TST.PL < STU.GR AND TST.PL > STU.GR - 0.5 THEN 2
  -- WHEN TST.PL > STU.GR THEN 3
  -- SPRING
  WHEN ROUND(GBS.SCR,2) < STU.GR THEN 1
  WHEN STU.GR = 1 AND ROUND(GBS.SCR,2) > 1 AND ROUND(GBS.SCR,2) < 1.5 THEN 2
  WHEN STU.GR = 1 AND ROUND(GBS.SCR,2) > 1.4 THEN 3
  WHEN ROUND(GBS.SCR,2) < STU.GR + 0.5 AND ROUND(GBS.SCR,2) > STU.GR THEN 2
  WHEN ROUND(GBS.SCR,2) > STU.GR + 0.5 THEN 3
END, --M
--'XTBL_TEST_SCORES.TEST_SCORE_TEXT' = CASE TST.PL
'XTBL_TEST_SCORES.TEST_SCORE_TEXT' = CASE ROUND(GBS.SCR,2)
  WHEN 0.3 THEN 'A'
  WHEN 0.6 THEN 'B'
  WHEN 0.9 THEN 'C'
  WHEN 1.2 THEN 'D'
  WHEN 1.4 THEN 'E'
  WHEN 1.5 THEN 'F'
  WHEN 1.6 THEN 'G'
  WHEN 1.8 THEN 'H'
  WHEN 1.9 THEN 'I'
  WHEN 2.3 THEN 'J'
  WHEN 2.6 THEN 'K'
  WHEN 2.9 THEN 'L'
  WHEN 3.3 THEN 'M'
  WHEN 3.6 THEN 'N'
  WHEN 3.9 THEN 'O'
  WHEN 4.3 THEN 'P'
  WHEN 4.6 THEN 'Q'
  WHEN 4.9 THEN 'R'
  WHEN 5.3 THEN 'S'
  WHEN 5.6 THEN 'T'
  WHEN 5.9 THEN 'U'
  WHEN 6.3 THEN 'V'
  WHEN 6.6 THEN 'W'
  WHEN 6.9 THEN 'X'
  WHEN 7.3 THEN 'Y'
  WHEN 7.6 THEN 'Z'
  ELSE 'No Score'
END, --N
'XTBL_TEST_SCORES.TEST_SCORE_VALUE' = '', --O
'XTBL_TEST_SCORES.TEST_RAW_SCORE' = '', --P
'XTBL_TESTS.TEST_CLASS' = 'Component', --Q
'XTBL_TESTS.TEST_NAME' = 'Fountas and Pinnell - Text Level', --R
'XTBL_TESTS.TEST_SUBGROUP' = 'Text Level', --S
'XTBL_TESTS.TEST_SUBJECT' = 'English Language Arts', --T
'XTBL_TESTS.TEST_VENDOR' = 'Morgan Hill', --U
'XTBL_TESTS.TEST_PRODUCT' = 'Fountas and Pinnell' --V
FROM STU
-- JOIN TST ON TST.PID = STU.ID
JOIN GBS ON(GBS.SC = STU.SC) AND (GBS.SN = STU.SN)
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.SC IN (2,6,8,9,10,11,12,15)
AND STU.GR > 0
AND STU.GR < 6
-- AND TST.TA = 'BL2021'
-- AND TST.ID = 'F&P'
AND GBS.AN in (902)
AND GBS.DC IS NOT NULL
