SELECT
COUNT (DISTINCT STU.ID)
FROM STU
JOIN GRD ON GRD.SN = STU.SN AND GRD.SC = STU.SC
JOIN CRS ON GRD.CN = CRS.CN
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.SC IN (20,21)
and grd.m1 in ('f','d','d-','d+','np','nc')
