SELECT
STU.ID,
ATT.SC,
School = ( select LOC.NM from LOC where ATT.SC = LOC.CD),
'DO ENEXA' = SUM(CASE WHEN ATT.AL = '3' THEN 1 ELSE 0 END),
'Emergency' = SUM(CASE WHEN ATT.AL = '4' THEN 1 ELSE 0 END),
'DO EXA' = SUM(CASE WHEN ATT.AL = '5' THEN 1 ELSE 0 END),
'Absnt UnxV' = SUM(CASE WHEN ATT.AL = '6' THEN 1 ELSE 0 END),
'NPS Absent' = SUM(CASE WHEN ATT.AL = '8' THEN 1 ELSE 0 END),
'Absent Unv' = SUM(CASE WHEN ATT.AL = 'A' THEN 1 ELSE 0 END),
'Dental' = SUM(CASE WHEN ATT.AL = 'D' THEN 1 ELSE 0 END),
'Med Xclusn' = SUM(CASE WHEN ATT.AL = 'E' THEN 1 ELSE 0 END),
'Funeral' = SUM(CASE WHEN ATT.AL = 'F' THEN 1 ELSE 0 END),
'DO HHAbsnt' = SUM(CASE WHEN ATT.AL = 'H' THEN 1 ELSE 0 END),
'Illness' = SUM(CASE WHEN ATT.AL = 'I' THEN 1 ELSE 0 END),
'In Office' = SUM(CASE WHEN ATT.AL = 'K' THEN 1 ELSE 0 END),
'Medical' = SUM(CASE WHEN ATT.AL = 'M' THEN 1 ELSE 0 END),
'Nurse Ofc' = SUM(CASE WHEN ATT.AL = 'N' THEN 1 ELSE 0 END),
'Other' = SUM(CASE WHEN ATT.AL = 'O' THEN 1 ELSE 0 END),
'Susp In Hs' = SUM(CASE WHEN ATT.AL = 'Q' THEN 1 ELSE 0 END),
'Suspension' = SUM(CASE WHEN ATT.AL = 'S' THEN 1 ELSE 0 END),
'Absent Unx' = SUM(CASE WHEN ATT.AL = 'U' THEN 1 ELSE 0 END),
'Absent Exc' = SUM(CASE WHEN ATT.AL = 'X' THEN 1 ELSE 0 END),
'Med Cnfdl' = SUM(CASE WHEN ATT.AL = 'Z' THEN 1 ELSE 0 END)
FROM ATT
JOIN STU ON ATT.SC = STU.SC AND ATT.SN = STU.SN
WHERE STU.DEL = 0
AND STU.SC IN (2,6,8,9,10,11,12,15,20,21,30,31,32)
GROUP BY STU.ID, STU.FN, STU.LN, ATT.SC
ORDER BY STU.ID

SELECT
AHS.ID,
AHS.SCL,
School = ( select LOC.NM from LOC where AHS.SCL = LOC.CD),
AHS.PR,
AHS.EN,
AHS.AB,
AHS.AE,
AHS.AU,
AHS.TD
FROM AHS
WHERE AHS.YR = '2020-2021'
ORDER BY AHS.ID
