SELECT
ID = STU.ID,
Name = STU.LN + ', ' + STU.FN,
Grade = STU.GR,
DIME = CASE (SELECT TOP(1) CD FROM PGM WHERE PGM.PID = STU.ID AND PGM.CD = 41)
  WHEN 41 THEN 'Y'
  ELSE 'N' END,
ELASCR2019_CAASPP =  ISNULL ((SELECT TOP (1) cast( SS as int) AS score FROM dbo.TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'SBAC') AND (TA = 'SPRG19') AND (PT = 1) ORDER BY TD DESC ),''),
MathSCR2019_CAASPP =  ISNULL ((SELECT TOP (1) cast( SS as int) AS score FROM dbo.TST WHERE (DEL = 0) AND (PID = stu.ID) AND (ID = 'SBAC') AND (TA = 'SPRG19') AND (PT = 2) ORDER BY TD DESC ),'')
FROM STU
WHERE STU.DEL = 0
AND STU.TG = ''
AND STU.SC = 10
AND STU.GR IN (8)
ORDER BY STU.SC, STU.GR, DIME, STU.LN, STU.FN
