SELECT
StudentID = STU.ID,
StudentLastName = STU.LN,
StudentFirstName = STU.FN,
STU.SC,
STU.GR AS 'Grade',
GRH.MK AS 'Last Semester Grade',
(SELECT TOP(1) MK FROM Aeries2018.dbo.GRH AS GRH18 WHERE GRH18.SN = STU18.SN AND GRH18.SC = STU18.SC AND GRH18.DEL = 0 AND GRH18.SC IN (31,32) AND GRH18.WM = 4 AND GRH18.CN = '313224') AS 'Last Year 1st Semester',
SPED = STU.U2
FROM STU 
JOIN Aeries2018.dbo.STU AS STU18
	ON STU.ID = STU18.ID 
JOIN GRH 
	ON(GRH.SN = STU.SN AND GRH.SC = STU.SC)
WHERE STU.TG = ''
AND STU.DEL = 0
AND STU.SC IN (31,32) 
AND GRH.CN = '313225'
AND GRH.WM = 4
AND GRH.DEL = 0
ORDER BY StudentID
