SELECT
*
FROM CNF
WHERE DT > '2020-08-01'
AND CO LIKE '%Home Visit%'
AND CD = 'C5'

--LIST CNF IF CNF.CD = 'C5' AND CNF.DT > '2020-08-14' AND CNF.CO : "HOME VISIT" 

SELECT 
*
FROM INV
WHERE CD IN ('RH', 'SG')

--LIST INV IF CD = 'SG' OR CD = 'RH'  

SELECT 
*
FROM VIS
WHERE CO LIKE '%Home Visit%'

--LIST VIS IF CO : "HOME VISIT" 

SELECT 
*
FROM SCHK
WHERE CO LIKE '%Home Visit%'

--LIST SCHK IF CO : "HOME VISIT" 